GET http://localhost:5000/makanan

###
GET http://localhost:5000/users/6

###
POST http://localhost:5000/makanan
Content-Type: application/json

{
    "nama": "Angger",
    "image": "https://cdn.discordapp.com/attachments/1133593391301677187/1133593631207477338/coca.png",
    "harga": "4.500"
}

###
PATCH http://localhost:5000/users/6
Content-Type: application/json

{
    "nama": "Fajar",
    "harga": "10000",
    "image": "351507"
}

###
DELETE http://localhost:5000/users/6

###
POST http://localhost:5000/feedbacks

###
GET http://localhost:5000/search?nama=Aqua